### ISSUE TITLE
the zero button should have the "0" to the left

### ISSUE THREAD

**Issue by JohnathanMarkSmith** [kamilskrzynski/calculator#1]
the zero button should have the "0" to the left

**Comment by kamilskrzynski** [comment]
Fixed, thank you for pointing it out :)

**Comment by JohnathanMarkSmith** [comment]
Hey @kamilskrzynski ,  You have a few more issues in this to make it work like the iOS Calc.  I have a fix for them all but I need to talk to you.. anyway you can please email me at PilotSmith69@gmail.com

**Comment by kamilskrzynski** [comment]
I will check it out and eventually fix all of them by myself, anyways thank you for pointing them out by making this issue

**Comment by JohnathanMarkSmith** [comment]
Thanks.. anyway to contact me please... I need your help
